# All the hyperparameters used in the training
EARLY_STOPPING_PATIENCE = 1e2
EPOCHS = int(5e4)
CHECKPOINT_PERIOD = 10
WORKERS = 8
BATCH_SIZE = int(7e2)
LEARNING_RATE = 0.001
EXP_BASE_NAME = "Sudoku_MLP"
WEIGHT_DECAY = 0.001
