# All the hyperparameters used in the training
EARLY_STOPPING_PATIENCE=610
EPOCHS=50
CHECKPOINT_PERIOD = 2
WORKERS = 4
BATCH_SIZE = 70
LEARNING_RATE = 0.0001
EXP_BASE_NAME = "Sudoku_MLP"
WEIGHT_DECAY = 0.0001